#use_frameworks!

platform :ios, '9.0'
inhibit_all_warnings!

target 'AMLeaksFinder_Example' do
  
  pod 'AMLeaksFinder', :path => '../'
  
  target 'AMLeaksFinder_Tests' do
    inherit! :search_paths
  end
end
